import type { MobileContext } from '../../types/context';
import type { ViewerConfigLike, ViewerInstance } from '../../types/viewerTypes';
import type { MobileUI } from './mobileUI';
export declare class GestureHandler {
    private viewer;
    private config;
    private mobileUI;
    private ctx;
    private deviceDetector;
    private touchStartX;
    private touchStartY;
    private touchEndX;
    private touchEndY;
    private touchStartTime;
    private touchEndTime;
    private isGestureEnabled;
    private minSwipeDistance;
    private maxSwipeTime;
    private pinchStartDistance;
    private pinchStartScale;
    private currentScale;
    private thumbnailsShowFlag;
    private _boundTouchStart;
    private _boundTouchMove;
    private _boundTouchEnd;
    private _listenersAttached;
    private gestureCallbacks;
    private debouncedPageChange;
    constructor(viewer: ViewerInstance, config: ViewerConfigLike, mobileUI: MobileUI | null, ctx?: MobileContext);
    init(): void;
    private addGestureListeners;
    private removeGestureListeners;
    private handleTouchStart;
    private handleTouchMove;
    private handleTouchEnd;
    private handleSwipe;
    private handleSwipeLeft;
    private handleSwipeRight;
    private handleSwipeUp;
    private handleSwipeDown;
    private getDistance;
    private executeCallbacks;
    private setThumbnailsShowFlag;
    onSwipeLeft(callback: () => void): void;
    onSwipeRight(callback: () => void): void;
    onSwipeUp(callback: () => void): void;
    onSwipeDown(callback: () => void): void;
    onPinchIn(callback: () => void): void;
    onPinchOut(callback: () => void): void;
    onDoubleTap(callback: () => void): void;
    enable(): void;
    disable(): void;
    updateMode(breakpoint: 'mobile' | 'tablet' | 'desktop'): void;
    updateSettings(settings: {
        minSwipeDistance?: number;
        maxSwipeTime?: number;
    }): void;
    destroy(): void;
}
