import type { MobileContext } from '../../types/context';
import type { DeviceInfo, OptimizationSettings, ResponsiveConfig, UISettings } from '../../types';
import type { ViewerConfigLike, ViewerInstance } from '../../types/viewerTypes';
export declare class Mobile {
    private viewer;
    private config;
    private crossViewer;
    private ctx;
    private lang;
    private mobileContext;
    private breakpointManager;
    private mobileUI;
    private touchHandler;
    private orientationHandler;
    private deviceDetector;
    private _ownsDeviceDetector;
    private mediaQuery;
    private gestureHandler;
    private currentBreakpoint;
    private isInitialized;
    constructor(viewer: ViewerInstance, config: ViewerConfigLike, ctx?: MobileContext | null);
    private getMobileContext;
    private getContextValue;
    private callContext;
    private getResponsiveRoot;
    private init;
    private setInitialBreakpoint;
    private setupEventListeners;
    private initializeModules;
    private applyInitialLayout;
    private handleBreakpointChange;
    private handleOrientationChange;
    private handleMediaQueryBreakpointChange;
    private handleScreenSizeChange;
    private filePathCheck;
    private getUrlParameterWithFragment;
    private getUrlSearchParams;
    private handleFileOpenLogic;
    private handleFileUrlNotAllowedError;
    private setupGestureCallbacks;
    private applyOptimizationSettings;
    private updateThumbnailSize;
    private toggleAnimations;
    private toggleGestures;
    private togglePinchZoom;
    private applyUISettings;
    private applyPortraitLayout;
    private applyLandscapeLayout;
    private emit;
    getStatus(): {
        isInitialized: boolean;
        currentBreakpoint: 'mobile' | 'desktop';
        deviceInfo: DeviceInfo;
        responsiveConfig: ResponsiveConfig;
        optimizationSettings: OptimizationSettings;
        uiSettings: UISettings;
    };
    destroy(): void;
}
