import type { ViewerConfigLike, ViewerInstance } from '../../types/viewerTypes';
import type { MobileUI } from './mobileUI';
interface TouchArea {
    element: HTMLElement | null;
    handlers: {
        tap?: (e: TouchEvent) => void;
        swipe?: (deltaX: number, deltaY: number) => void;
        longPress?: () => void;
    };
}
export declare class TouchHandler {
    private viewer;
    private mobileUI;
    private touchStartX;
    private touchStartY;
    private touchEndX;
    private touchEndY;
    private touchStartTime;
    private touchEndTime;
    private isTouching;
    private touchThreshold;
    private tapThreshold;
    private longPressThreshold;
    private longPressTimer;
    private touchArea;
    private isDragging;
    private dragThreshold;
    /** touchend에서 파일 탐색기를 열었을 때 합성 click 이벤트의 이중 트리거를 방지하는 플래그 */
    private _filePickerPending;
    private eventHandlers;
    private touchContainer;
    private pinchZoomElements;
    private doubleTapElements;
    private doubleTapHandlers;
    touchAreas: Record<string, TouchArea>;
    constructor(viewer: ViewerInstance, _config: ViewerConfigLike, mobileUI?: MobileUI | null);
    setMobileUI(mobileUI: MobileUI): void;
    /** MobileUI에 설정된 현재 뷰어 사용 (문서 열림 후 CrepasViewer, 그 전에는 constructor 인자) */
    private getViewer;
    private init;
    private getRoot;
    private queryRole;
    private getHeaderElement;
    private getFooterElement;
    private getContentElement;
    private getThumbnailsSectionElement;
    private getSearchComponentElement;
    private getContentThumbnailsIconElement;
    private setupTouchAreas;
    private shouldPreventDefaultInViewerTouch;
    private addTouchListeners;
    refreshTouchListeners(): void;
    private removeTouchListeners;
    setupBackgroundTouchHandler(viewerContainer: HTMLElement): void;
    removeBackgroundTouchListeners(viewerContainer: HTMLElement): void;
    private handleBackgroundClick;
    private handleTouchStart;
    private handleTouchMove;
    private handleTouchEnd;
    private handleTouchCancel;
    private identifyTouchArea;
    private processTouchEnd;
    private handleTap;
    private handleSwipe;
    private startLongPressTimer;
    private cancelLongPressTimer;
    private handleLongPress;
    private handleContentTap;
    private handleContentSwipe;
    private handleHeaderTap;
    private handleHeaderLongPress;
    private handleThumbnailsTap;
    private handleThumbnailsSwipe;
    private handleSearchComponentTap;
    private handleSearchComponentLongPress;
    private maintainSearchIconActive;
    updateTouchAreas(): void;
    private toggleUI;
    private toggleSearchUI;
    private showSearchUI;
    private hideSearchUI;
    private showUI;
    hideUI(): void;
    private hideTitleTooltip;
    updateMode(breakpoint: 'mobile' | 'tablet' | 'desktop'): void;
    preventDoubleTabZoom(element: HTMLElement): void;
    setupPinchZoomPrevention(): void;
    private preventPinchZoom;
    private preventGesture;
    private preventWheelZoom;
    destroy(): void;
}
export {};
